package present.server.model.group;

import com.google.common.collect.ImmutableList;
import com.googlecode.objectify.Key;
import java.util.List;
import present.server.model.util.Coordinates;
import present.server.tool.ChooseWelcomeGroupCities;

import static com.googlecode.objectify.ObjectifyService.ofy;
import static java.util.Comparator.comparingDouble;

/**
 * We add new users to their nearest welcome group.
 *
 * Generated by {@link ChooseWelcomeGroupCities}.
 *
 * @author Bob Lee (bob@present.co)
 */
public class WelcomeGroup {

  public static final List<WelcomeGroup> ALL = ImmutableList.of(
      new WelcomeGroup("a99e028e-9567-5406-82f9-18e7c73dd94a", "Milwaukee", "Wisconsin", new Coordinates(43.0633, -87.9667)),
      new WelcomeGroup("f012b821-4c15-b155-2771-6fe8d5a5970d", "Madison", "Wisconsin", new Coordinates(43.0878, -89.4299)),
      new WelcomeGroup("f22c4529-c7d3-ab98-2c67-adbeeed5355e", "Green Bay", "Wisconsin", new Coordinates(44.5207, -87.9842)),
      new WelcomeGroup("34c42eea-a852-4aa4-1e5d-c137ab40130c", "Seattle", "Washington", new Coordinates(47.6205, -122.3509)),
      new WelcomeGroup("6f6140b5-8382-ff4b-d7fb-88bdbfbd3d30", "Spokane", "Washington", new Coordinates(47.6669, -117.43329999999999)),
      new WelcomeGroup("42793c22-535c-fe1f-9213-fa7bb315f9ce", "Virginia Beach", "Virginia", new Coordinates(36.78, -76.02520000000001)),
      new WelcomeGroup("563f6520-d9f2-185b-3dd9-878a982bc9ab", "Richmond", "Virginia", new Coordinates(37.531400000000005, -77.476)),
      new WelcomeGroup("e6dbe697-a356-a2cd-1e6d-7c5beaeb175d", "Salt Lake City", "Utah", new Coordinates(40.7769, -111.931)),
      new WelcomeGroup("eb532a63-8fe9-8d86-6f97-582a0fe926c7", "Houston", "Texas", new Coordinates(29.786600000000004, -95.3909)),
      new WelcomeGroup("5e5d6562-3fd2-c6cc-a7f5-5832fd5ce0c2", "San Antonio", "Texas", new Coordinates(29.472399999999997, -98.5251)),
      new WelcomeGroup("b64fa2b3-307f-1c64-2985-bc198a4bd38c", "Dallas", "Texas", new Coordinates(32.7933, -96.76650000000001)),
      new WelcomeGroup("a2ccf5f9-f254-08b8-0f45-ba0d5e270d74", "Austin", "Texas", new Coordinates(30.3039, -97.7544)),
      new WelcomeGroup("2919fe43-25c2-ebb3-caa9-13a6725d16ba", "El Paso", "Texas", new Coordinates(31.8484, -106.427)),
      new WelcomeGroup("8b965a60-9886-a81c-5899-93266a966b81", "Corpus Christi", "Texas", new Coordinates(27.7543, -97.1734)),
      new WelcomeGroup("e0fa7e12-1780-d390-59cc-d0ffa36d94f5", "Laredo", "Texas", new Coordinates(27.5604, -99.4892)),
      new WelcomeGroup("d0937ec0-1ab0-d7a6-42f0-f1ac33aaccb6", "Lubbock", "Texas", new Coordinates(33.5656, -101.8867)),
      new WelcomeGroup("8ccdc2d1-5114-28c4-e430-a3703bd42b30", "Amarillo", "Texas", new Coordinates(35.1999, -101.8302)),
      new WelcomeGroup("12c1d2e7-0814-cf52-50ba-645efb5c0d91", "Brownsville", "Texas", new Coordinates(25.9991, -97.455)),
      new WelcomeGroup("f416c249-92e5-bc3a-8385-713e5524312e", "Midland", "Texas", new Coordinates(32.0246, -102.1135)),
      new WelcomeGroup("26581a22-ab93-dd6e-a870-b2673d6296cc", "Abilene", "Texas", new Coordinates(32.4545, -99.73810000000002)),
      new WelcomeGroup("42c6e2fe-b7a0-8a2c-0c04-f2b8fa0c9ea1", "Beaumont", "Texas", new Coordinates(30.084900000000005, -94.1453)),
      new WelcomeGroup("ab55aa7e-7952-2492-f02a-94e2b79f718d", "College Station", "Texas", new Coordinates(30.5852, -96.2964)),
      new WelcomeGroup("fa49eb89-490b-cea1-0744-7db0ab26f3a7", "Tyler", "Texas", new Coordinates(32.3173, -95.3059)),
      new WelcomeGroup("fc2f0e39-ce0d-6c82-051e-e3ea2709bdc0", "Wichita Falls", "Texas", new Coordinates(33.9067, -98.52590000000001)),
      new WelcomeGroup("bbab6109-cf1d-7a71-7f12-a41dbd4be4cc", "San Angelo", "Texas", new Coordinates(31.441100000000002, -100.4505)),
      new WelcomeGroup("24620623-3921-40c2-087d-1e213296abc5", "Nashville", "Tennessee", new Coordinates(36.171800000000005, -86.785)),
      new WelcomeGroup("7bf557a3-4acb-91c0-e93a-f79bc71504ed", "Memphis", "Tennessee", new Coordinates(35.1028, -89.9774)),
      new WelcomeGroup("01ba5a49-df5d-e25e-f3f3-162fe55e8225", "Knoxville", "Tennessee", new Coordinates(35.9707, -83.9493)),
      new WelcomeGroup("d2963c07-156d-f980-b966-d52105043780", "Chattanooga", "Tennessee", new Coordinates(35.066, -85.2484)),
      new WelcomeGroup("6319e70e-fc7a-facc-af91-f22338f3b5a5", "Sioux Falls", "South Dakota", new Coordinates(43.53830000000001, -96.732)),
      new WelcomeGroup("d2bf44a0-2885-1674-da30-28eb1c1b61d4", "Charleston", "South Carolina", new Coordinates(32.8179, -79.959)),
      new WelcomeGroup("db4b29ee-9353-5795-29e4-b01ec4c1c39e", "Columbia", "South Carolina", new Coordinates(34.0291, -80.898)),
      new WelcomeGroup("331faad1-f4e1-69f5-db3e-14c91bfe414a", "Philadelphia", "Pennsylvania", new Coordinates(40.0094, -75.1333)),
      new WelcomeGroup("2b0f10b0-c340-5ee0-694d-16a7f809d94f", "Pittsburgh", "Pennsylvania", new Coordinates(40.4398, -79.9766)),
      new WelcomeGroup("9b889b2c-1763-5065-b659-218a64e1a8bd", "Portland", "Oregon", new Coordinates(45.537, -122.65)),
      new WelcomeGroup("6b4e29ec-875e-f026-5ec0-cb6ad42ef859", "Eugene", "Oregon", new Coordinates(44.0567, -123.1162)),
      new WelcomeGroup("40e0084d-b745-d0bb-3fb8-318eca343a0a", "Oklahoma City", "Oklahoma", new Coordinates(35.4671, -97.5137)),
      new WelcomeGroup("21fb9531-e16a-a0b4-0a61-87853c637487", "Tulsa", "Oklahoma", new Coordinates(36.1279, -95.9023)),
      new WelcomeGroup("dd4d03bb-db04-5f78-4132-ccad6fd91005", "Columbus", "Ohio", new Coordinates(39.9852, -82.9848)),
      new WelcomeGroup("bc5b76dc-313a-9469-2481-9840dbe0fb00", "Cleveland", "Ohio", new Coordinates(41.4785, -81.6794)),
      new WelcomeGroup("48331fcc-d4bf-adf1-507a-3d67e3bee3ea", "Cincinnati", "Ohio", new Coordinates(39.14020000000001, -84.5058)),
      new WelcomeGroup("43f30f22-4a9c-e35d-1929-58b6f472c10e", "Fargo", "North Dakota", new Coordinates(46.8652, -96.829)),
      new WelcomeGroup("09f19a78-ef94-8dc6-6d23-438717a6ceca", "Charlotte", "North Carolina", new Coordinates(35.2078, -80.831)),
      new WelcomeGroup("d4d54602-b35a-b4fe-0db0-50fca2c80d26", "Raleigh", "North Carolina", new Coordinates(35.8306, -78.6418)),
      new WelcomeGroup("aee78f4b-c842-47f8-c450-b646d4a472c1", "Greensboro", "North Carolina", new Coordinates(36.0951, -79.827)),
      new WelcomeGroup("02328d4b-89c1-e8b0-4af6-b2bb185d2ac0", "Wilmington", "North Carolina", new Coordinates(34.2092, -77.88580000000002)),
      new WelcomeGroup("3b56df35-6ddd-0436-e55a-6d1e84fc1653", "New York", "New York", new Coordinates(40.6635, -73.9387)),
      new WelcomeGroup("3e3372e0-5f2b-0c23-a750-41e1449ce0d4", "Buffalo", "New York", new Coordinates(42.8925, -78.8597)),
      new WelcomeGroup("29cd78b5-59e6-2999-a3f0-1096a190fbb3", "Rochester", "New York", new Coordinates(43.1699, -77.6169)),
      new WelcomeGroup("3632e8b5-04f3-7358-cd10-857edeb99603", "Syracuse", "New York", new Coordinates(43.041, -76.1436)),
      new WelcomeGroup("2dc99408-a78e-7e95-519a-c4ef4293e486", "Albuquerque", "New Mexico", new Coordinates(35.1056, -106.6474)),
      new WelcomeGroup("a11e6168-71ef-596c-ac84-6a8558f45bf9", "Las Vegas", "Nevada", new Coordinates(36.2292, -115.2601)),
      new WelcomeGroup("a9e43095-0e0c-1aa3-01eb-ab06aa68d52e", "Reno", "Nevada", new Coordinates(39.5491, -119.8499)),
      new WelcomeGroup("a3969205-ba2f-737a-e32c-946012b68b69", "Omaha", "Nebraska", new Coordinates(41.2644, -96.0451)),
      new WelcomeGroup("85d28eb4-17b3-ae53-3a51-3c49d4395053", "Billings", "Montana", new Coordinates(45.7885, -108.5499)),
      new WelcomeGroup("b6ee321a-d429-5885-10dc-bb319accaba7", "Kansas City", "Missouri", new Coordinates(39.1251, -94.551)),
      new WelcomeGroup("3e145b96-d89b-602b-3627-efb2d1ec5541", "St. Louis", "Missouri", new Coordinates(38.6357, -90.2446)),
      new WelcomeGroup("d6a9b152-e7b0-1fbc-ed29-8d21c3553008", "Springfield", "Missouri", new Coordinates(37.1942, -93.2913)),
      new WelcomeGroup("db4b29ee-9353-5795-29e4-b01ec4c1c39e", "Columbia", "Missouri", new Coordinates(38.9473, -92.3264)),
      new WelcomeGroup("4f2861f7-7e0a-92e4-80d2-abb32639e91b", "Jackson", "Mississippi", new Coordinates(32.3158, -90.2128)),
      new WelcomeGroup("37d5cc99-85b7-2f76-eed1-5f0ca11880dd", "Minneapolis", "Minnesota", new Coordinates(44.9633, -93.2683)),
      new WelcomeGroup("29cd78b5-59e6-2999-a3f0-1096a190fbb3", "Rochester", "Minnesota", new Coordinates(44.0154, -92.4772)),
      new WelcomeGroup("fb7cbb91-ace6-8332-9cbb-138076de4a23", "Detroit", "Michigan", new Coordinates(42.383, -83.1022)),
      new WelcomeGroup("0304d495-9046-50da-ab96-df44fe184f7a", "Grand Rapids", "Michigan", new Coordinates(42.9612, -85.6556)),
      new WelcomeGroup("ddf5a0fb-2e15-77d6-f4ca-8d82e488f1ce", "Boston", "Massachusetts", new Coordinates(42.332, -71.0202)),
      new WelcomeGroup("1a687c09-afde-9b60-85ee-8785210fe6ae", "New Orleans", "Louisiana", new Coordinates(30.053400000000003, -89.9345)),
      new WelcomeGroup("ef8ae6fa-d9ea-3123-0355-6c262ff39c18", "Baton Rouge", "Louisiana", new Coordinates(30.4422, -91.1309)),
      new WelcomeGroup("f466c52a-0332-5868-2651-ac583fcde776", "Shreveport", "Louisiana", new Coordinates(32.4669, -93.7922)),
      new WelcomeGroup("dbf7b344-2de1-915b-ac9e-e78b174ba158", "Louisville", "Kentucky", new Coordinates(38.1654, -85.6474)),
      new WelcomeGroup("5bde3995-1031-a1dd-a967-e1e298c8fe47", "Lexington", "Kentucky", new Coordinates(38.0407, -84.4583)),
      new WelcomeGroup("1da356fd-9577-5c21-ef17-81e3a3e1bd78", "Wichita", "Kansas", new Coordinates(37.6907, -97.3459)),
      new WelcomeGroup("5d0ee3b3-203b-2fd4-70b7-fc503447f235", "Des Moines", "Iowa", new Coordinates(41.5726, -93.6102)),
      new WelcomeGroup("9c8d34e3-486b-76e2-1f56-4a0f274a5a78", "Cedar Rapids", "Iowa", new Coordinates(41.967, -91.67780000000002)),
      new WelcomeGroup("8cb63f3d-fe6f-cede-4027-9868dd5a044d", "Davenport", "Iowa", new Coordinates(41.5541, -90.604)),
      new WelcomeGroup("b6717a3d-2249-e972-0171-3d2d9c51f69d", "Indianapolis", "Indiana", new Coordinates(39.7767, -86.1459)),
      new WelcomeGroup("4dc36dd0-435e-9dba-84f8-94bddc2f8e6e", "Fort Wayne", "Indiana", new Coordinates(41.0882, -85.1439)),
      new WelcomeGroup("e72d457b-d7d2-a9d7-d232-3c0acefcaeb1", "Evansville", "Indiana", new Coordinates(37.9877, -87.5347)),
      new WelcomeGroup("9013dad2-5b2f-0b17-b03c-20121d289042", "South Bend", "Indiana", new Coordinates(41.6769, -86.269)),
      new WelcomeGroup("364346a7-c58a-5b5f-3dd3-3a5137292e25", "Chicago", "Illinois", new Coordinates(41.8376, -87.6818)),
      new WelcomeGroup("d6a9b152-e7b0-1fbc-ed29-8d21c3553008", "Springfield", "Illinois", new Coordinates(39.7911, -89.6446)),
      new WelcomeGroup("de09b4ea-25c3-d8bf-3f0c-56e7449829e4", "Peoria", "Illinois", new Coordinates(40.7515, -89.6174)),
      new WelcomeGroup("e3ae8ee1-863c-6487-2555-1121c5441b54", "Boise", "Idaho", new Coordinates(43.6002, -116.2317)),
      new WelcomeGroup("6e9f9f77-8fcd-827f-6334-ea7cc9183967", "Honolulu", "Hawaii", new Coordinates(21.3243, -157.8476)),
      new WelcomeGroup("143db725-c635-78a2-711d-1dfa587469f1", "Atlanta", "Georgia", new Coordinates(33.7629, -84.4227)),
      new WelcomeGroup("dd4d03bb-db04-5f78-4132-ccad6fd91005", "Columbus", "Georgia", new Coordinates(32.5102, -84.8749)),
      new WelcomeGroup("fe228fea-8e5e-8f88-0089-40d04b34754e", "Augusta", "Georgia", new Coordinates(33.3655, -82.0734)),
      new WelcomeGroup("793c9003-08a2-c2e5-3724-59c8a552b827", "Macon", "Georgia", new Coordinates(32.808800000000005, -83.6942)),
      new WelcomeGroup("f7ab3ce0-82d6-e298-6d17-75178e9b1b3b", "Savannah", "Georgia", new Coordinates(32.0025, -81.1536)),
      new WelcomeGroup("3eb6dc22-c052-83b6-f26f-9da6d013d579", "Athens", "Georgia", new Coordinates(33.9496, -83.3701)),
      new WelcomeGroup("980d9bed-3e2d-a74a-b559-a378e77029b6", "Jacksonville", "Florida", new Coordinates(30.336900000000004, -81.6616)),
      new WelcomeGroup("5fe0d921-976b-c468-e050-cc3576dfb7cd", "Miami", "Florida", new Coordinates(25.7752, -80.2086)),
      new WelcomeGroup("3dee022d-0aed-5705-5cd9-73d4890f44b4", "Tampa", "Florida", new Coordinates(27.9701, -82.4797)),
      new WelcomeGroup("80048147-0d72-1ad6-1113-edc55ba01532", "Orlando", "Florida", new Coordinates(28.4166, -81.2736)),
      new WelcomeGroup("48b034b0-23db-c8cd-50e6-c2ba902537a3", "Tallahassee", "Florida", new Coordinates(30.4551, -84.2534)),
      new WelcomeGroup("f3b5dc16-cd59-060c-d881-31dc79f6f67c", "Port St. Lucie", "Florida", new Coordinates(27.2806, -80.3883)),
      new WelcomeGroup("6d661771-1b47-b6ae-2408-7f43f06b9129", "Cape Coral", "Florida", new Coordinates(26.6432, -81.9974)),
      new WelcomeGroup("2a7e3761-1362-24f1-f15f-57c6ccb2bbcf", "Gainesville", "Florida", new Coordinates(29.6788, -82.3461)),
      new WelcomeGroup("e0d293f8-67b5-27ab-815e-a019dfcfcfa2", "Washington", "District of Columbia", new Coordinates(38.9041, -77.0172)),
      new WelcomeGroup("8a8f9c2c-9eee-e8d8-7dab-fd39b34f7452", "Denver", "Colorado", new Coordinates(39.7619, -104.8811)),
      new WelcomeGroup("c839efa8-e014-315d-c5a8-9cf911d10229", "Colorado Springs", "Colorado", new Coordinates(38.86730000000001, -104.7607)),
      new WelcomeGroup("f9659fd5-1d53-5cac-8032-d678b813e8ba", "Los Angeles", "California", new Coordinates(34.0194, -118.4108)),
      new WelcomeGroup("dd5d5117-8570-76be-48d2-3d017f1dc2bb", "San Diego", "California", new Coordinates(32.8153, -117.13500000000002)),
      new WelcomeGroup("b0ffac96-6ded-88a8-6c20-80dce8fd61a4", "San Jose", "California", new Coordinates(37.2967, -121.81890000000001)),
      new WelcomeGroup("dfd52aeb-767b-3180-aefa-68629c992ac5", "San Francisco", "California", new Coordinates(37.7272, -123.0322)),
      new WelcomeGroup("07b00a7b-0892-65e4-93c0-f1ccf19fc72d", "Fresno", "California", new Coordinates(36.7836, -119.79340000000002)),
      new WelcomeGroup("6cd2548d-dfcc-1fa3-02cb-3b73b32880d7", "Sacramento", "California", new Coordinates(38.5666, -121.46859999999998)),
      new WelcomeGroup("c25188a4-7de0-de65-f55a-c6a96d005f1a", "Bakersfield", "California", new Coordinates(35.3212, -119.0183)),
      new WelcomeGroup("e07a27a3-e98a-03d8-f7a1-340d2bc49a88", "Santa Maria", "California", new Coordinates(34.9332, -120.4438)),
      new WelcomeGroup("9deb7cea-e461-d5a8-3a7f-8ac455bd106d", "Little Rock", "Arkansas", new Coordinates(34.7254, -92.3586)),
      new WelcomeGroup("57ae957b-611f-6e56-adef-5008dafc7ff3", "Phoenix", "Arizona", new Coordinates(33.5722, -112.0901)),
      new WelcomeGroup("4df2197c-e454-6263-cd66-43c5c10050f2", "Tucson", "Arizona", new Coordinates(32.1531, -110.8706)),
      new WelcomeGroup("6c4f18f2-9bc6-3345-df14-abc63cfdc1ff", "Anchorage", "Alaska", new Coordinates(61.1743, -149.2843)),
      new WelcomeGroup("f9226a5b-296f-2573-7105-530986cd17a9", "Birmingham", "Alabama", new Coordinates(33.5274, -86.799)),
      new WelcomeGroup("3e1729ba-f309-1807-9256-e875c44336c1", "Montgomery", "Alabama", new Coordinates(32.3472, -86.2661)),
      new WelcomeGroup("33d6d913-2326-1144-b4e8-95bcd199ed90", "Huntsville", "Alabama", new Coordinates(34.699, -86.673)),
      new WelcomeGroup("4d30812f-2317-09c2-33d9-bc3011ddf43e", "Mobile", "Alabama", new Coordinates(30.6684, -88.1002)),
      new WelcomeGroup("9b889b2c-1763-5065-b659-218a64e1a8bd", "Portland", "Maine", new Coordinates(43.6590588, -70.2622418)),
      new WelcomeGroup("a332a445-d8d6-b835-b11d-d9d428e1d351", "Burlington", "Vermont", new Coordinates(44.47767830000001, -73.215244)),
      new WelcomeGroup("d2bf44a0-2885-1674-da30-28eb1c1b61d4", "Charleston", "West Virginia", new Coordinates(38.3493632, -81.6337592))
  );

  public final String uuid;
  public final String city;
  public final String state;
  public final Coordinates location;

  WelcomeGroup(String uuid, String city, String state, Coordinates location) {
    this.uuid = uuid;
    this.city = city;
    this.state = state;
    this.location = location;
  }

  public Key<Group> key() {
    return Key.create(Group.class, uuid);
  }

  public Group group() {
    return ofy().load().type(Group.class).id(uuid).now();
  }

  /** Finds the nearest welcome group. */
  public static Key<Group> nearestTo(Coordinates location) {
    return ALL.stream().min(comparingDouble(g -> g.location.distanceTo(location))).get().key();
  }
}
