export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

//user
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

//group
export const LOAD_SAVED_GROUP_SUCCESS = "LOAD_SAVED_GROUP_SUCCESS";
export const LOAD_GROUP_SUCCESS = "LOAD_GROUP_SUCCESS";
export const LOAD_GROUP_COMMENTS_SUCCESS = "LOAD_GROUP_COMMENTS_SUCCESS";
export const LOAD_MEMBER_REQUESTS = "LOAD_MEMBER_REQUESTS";

//groups
export const LOAD_NEARBY_GROUPS_SUCCESS= "LOAD_NEARBY_GROUPS_SUCCESS";

//activity
export const LOAD_NOTIFICATION_SUCCESS= "LOAD_NOTIFICATION_SUCCESS";

//inbox
export const LOAD_INBOX_SUCCESS= "LOAD_INBOX_SUCCESS";

//SOCKET
export const LOAD_SOCKET_SUCCESS = "LOAD_SOCKET_SUCCESS";
